[package]
name = "stobot"
version = "0.9.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "~0.11"
serde = "~1.0"
serde-aux = "~4.3"
serde_json = "~1.0"
regex = "~1.10"
chrono = "~0.4"
chrono-tz = "~0.8"

[dependencies.clap]
version = "~4.4"
features = ["derive"]

#[dependencies.openssl]
#version = "0.10"
#features = ["vendored"]

[dependencies.serenity]
version = "~0.12"
default-features = false
features = ["client", "gateway", "rustls_backend", "model", "cache", "http"]

[dependencies.tokio]
version = "~1.35"
features = ["macros", "rt-multi-thread"]
